=== kazrulit/xmlParser/src/main/resources/configs/shop.dtd
<!ELEMENT shop (category)>
<!ELEMENT category (sub_category)>
<!ELEMENT sub_category (good)>
<!ELEMENT good (product_name, provider, model, date, color, price)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT provider (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== kazrulit/xmlParser/src/main/resources/configs/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "shop.dtd">
<shop xmlns="http://www.epam.kz"
      xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
      xsd:schemaLocation="shop.xsd">
    <category>
        <sub_category>
            <good>
                <product_name>tovar1</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
            <good>
                <product_name>tovar3</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
        </sub_category>
        <sub_category>
            <good>
                <product_name>tovar11</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
            <good>
                <product_name>tovar12</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
        </sub_category>
    </category>
    <category>
        <sub_category>
            <good>
                <product_name>tovar6</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
            <good>
                <product_name>tovar2</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
        </sub_category>
        <sub_category>
            <good>
                <product_name>tovar3</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
            <good>
                <product_name>tovar5</product_name>
                <provider>China</provider>
                <model>ad123</model>
                <date>29-12-2015</date>
                <color>red</color>
                <price>123</price>
            </good>
        </sub_category>
    </category>
</shop>
